modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="whooosh" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Whooosh!" #mandatory
credits="Coda" #optional
description='''Whooosh! adds configurable wind particles.'''
