modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/Coda1552/Breezy/issues"

[[mods]]
modId="breezy"
version = "${file.jarVersion}"
displayName = "Breezy"
displayURL="https://modrinth.com/mod/breezy"
logoFile="logo.png"
credits="Mr. Esuoh, VakyPanda, Mango, Ezae10, DavigJ"
authors="codyhuh, Probleyes"
itemIcon = "breezy:hot_air_balloon"
configBackground = "minecraft:textures/block/orange_wool.png"

description='''A unique approach to hot air balloons!'''

[[dependencies.breezy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.breezy]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.breezy]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.1.40,)"
ordering = "NONE"
side = "BOTH"