modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="wind" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Wind:tm:" #mandatory
credits="Coda" #optional
description=''''''
